import sys
sys.path.insert(0, "/home/mao/.claude/plugins/marketplaces/maoqb-skills/skills/drawio-diagrams/scripts")
from drawio import Sequence

# ─── Diagram 1: 并发加载时序 ─────────────────────────────────────────────────
sq1 = Sequence("release_config_lib 并发加载流程")

main      = sq1.participant("main.go")
rcm       = sq1.participant("ReadReleaseConfigMaps")
ctx       = sq1.participant("loadContext\n(goroutine 池)")
dir_walk  = sq1.participant("WalkTextprotoFiles")
decl_r    = sq1.participant("declReader\n(×NumCPU)")
cont_r    = sq1.participant("contribReader\n(×NumCPU)")
val_r     = sq1.participant("valueReader\n(×NumCPU)")
info_h    = sq1.participant("infoHandler\n(×1)")
finalize  = sq1.participant("Finalize")

sq1.message(main, rcm, "ReadReleaseConfigMaps(\n  mapPaths, targetRelease, …)")
sq1.message(rcm, ctx, "createLoadContext()\n启动 NumCPU 个 goroutine")
sq1.message(rcm, dir_walk, "LoadReleaseConfigMap()\n遍历每个 map 目录")
sq1.message(dir_walk, decl_r, "declReaderChan ← {Map, Path}\n(flag_declarations/*.textproto)", kind="async")
sq1.message(dir_walk, cont_r, "contribReaderChan ← {Map, Path}\n(release_configs/*.textproto)", kind="async")
sq1.message(dir_walk, val_r, "valueReaderChan ← {Map, ConfigName, Path}\n(flag_values/<RELEASE>/*.textproto)", kind="async")
sq1.message(decl_r, info_h, "infoHandlerChan ← {decl: FlagArtifact}", kind="async")
sq1.message(cont_r, info_h, "infoHandlerChan ← {contrib: ReleaseConfigContribution}", kind="async")
sq1.message(val_r, info_h, "infoHandlerChan ← {value: FlagValue}", kind="async")
sq1.message(info_h, info_h, "写入 Map.FlagArtifactsForDecls /\nReleaseConfigContributions", kind="self")
sq1.message(rcm, rcm, "close(declReaderChan)\nclose(contribReaderChan)\nclose(valueReaderChan)", kind="self")
sq1.message(rcm, finalize, "Finalize(ctx, targetRelease)\n合并所有 map 数据")
sq1.message(finalize, finalize, "合并 FlagArtifacts\n构建 ReleaseConfigs map\n解析 Aliases → OtherNames", kind="self")
sq1.message(finalize, rcm, "return nil", kind="return")
sq1.message(rcm, main, "return *ReleaseConfigs", kind="return")

sq1.save("/home/mao/code/android-16.0.0_r4/release_config/release_config_loading.drawio")
sq1.save_svg("/home/mao/code/android-16.0.0_r4/release_config/release_config_loading.svg")
print("Saved loading sequence")

# ─── Diagram 2: GenerateReleaseConfig 继承解析时序 ────────────────────────────
sq2 = Sequence("GenerateReleaseConfig 继承解析流程")

caller   = sq2.participant("caller\n(main.go)")
gc       = sq2.participant("GenerateReleaseConfig\n(config)")
gc_root  = sq2.participant("GenerateReleaseConfig\n(root, 递归)")
gc_inh   = sq2.participant("GenerateReleaseConfig\n(inherit, 递归)")
inherit  = sq2.participant("InheritConfig")
contrib  = sq2.participant("contrib 循环\n(FlagValues)")
output   = sq2.participant("WriteMakefile /\nWriteArtifact")

sq2.message(caller, gc, "GenerateReleaseConfig(configs)")
sq2.message(gc, gc, "compileInProgress = true\nClone FlagArtifacts from configs", kind="self")
sq2.message(gc, gc_root, "GetReleaseConfig('root')\n→ GenerateReleaseConfig(root)")
sq2.message(gc_root, gc_root, "处理 root 的 MANUAL 标志", kind="self")
sq2.message(gc_root, gc, "return ReleaseConfigArtifact", kind="return")
sq2.message(gc, inherit, "InheritConfig(root_config)\n拷贝非 MANUAL_NO_INHERIT 标志值")
sq2.message(inherit, gc, "return nil", kind="return")
sq2.message(gc, gc_inh, "GetReleaseConfig(inherit_name)\n→ GenerateReleaseConfig(inherit)")
sq2.message(gc_inh, gc_inh, "递归处理继承链", kind="self")
sq2.message(gc_inh, gc, "return ReleaseConfigArtifact", kind="return")
sq2.message(gc, inherit, "InheritConfig(iConfig)\n合并 FlagArtifacts")
sq2.message(inherit, gc, "return nil", kind="return")
sq2.message(gc, contrib, "遍历 Contributions\n应用 FlagValues")
sq2.message(contrib, contrib, "fa.UpdateValue(value)\n追加 Tracepoint", kind="self")
sq2.message(contrib, gc, "return", kind="return")
sq2.message(gc, gc, "去重 RELEASE_ACONFIG_VALUE_SETS\n构建 PartitionBuildFlags\n填充 ReleaseConfigArtifact", kind="self")
sq2.message(gc, caller, "return nil", kind="return")
sq2.message(caller, output, "WriteMakefile() /\nWriteArtifact()")
sq2.message(output, caller, "return nil", kind="return")

sq2.save("/home/mao/code/android-16.0.0_r4/release_config/release_config_generate.drawio")
sq2.save_svg("/home/mao/code/android-16.0.0_r4/release_config/release_config_generate.svg")
print("Saved generate sequence")

# ─── Diagram 3: 编译期完整流程 ────────────────────────────────────────────────
sq3 = Sequence("编译期 release_config 完整流程")

lunch    = sq3.participant("lunch\n(用户)")
kati     = sq3.participant("Kati\n(release_config.mk)")
rc_bin   = sq3.participant("release-config-internal\n(out/release-config)")
rc_lib   = sq3.participant("release_config_lib")
soong    = sq3.participant("Soong\n(后续编译)")

sq3.message(lunch, kati, "lunch aosp_cf-trunk_staging-eng\n设置 TARGET_PRODUCT / TARGET_RELEASE / TARGET_BUILD_VARIANT")
sq3.message(kati, kati, "组装 _protobuf_map_files 列表\n写 maps_list-<product>.txt", kind="self")
sq3.message(kati, rc_bin, "KATI_shell_no_rerun out/release-config \\\n  --product … --release … --variant …\n  --maps-file … --hashfile …")
sq3.message(rc_bin, rc_lib, "ReadReleaseConfigMaps()\n(并发读取所有 textproto)")
sq3.message(rc_lib, rc_bin, "return *ReleaseConfigs", kind="return")
sq3.message(rc_bin, rc_lib, "GetReleaseConfig(targetRelease)\n→ GenerateReleaseConfig()")
sq3.message(rc_lib, rc_bin, "return *ReleaseConfig", kind="return")
sq3.message(rc_bin, rc_bin, "WriteMakefile(\n  release_config-<product>.varmk)", kind="self")
sq3.message(rc_bin, rc_bin, "WriteHashFile(files_used.hash)", kind="self")
sq3.message(rc_bin, kati, "exit 0", kind="return")
sq3.message(kati, kati, "include release_config-<product>.varmk\n→ ALL_RELEASE_CONFIGS_FOR_PRODUCT\n→ RELEASE_* 变量全部生效", kind="self")
sq3.message(kati, soong, "传递 --maps-file、--hashfile\n供 Soong 生成额外产物\n(all_release_configs-*.pb 等)")
sq3.message(soong, kati, "构建完成", kind="return")

sq3.save("/home/mao/code/android-16.0.0_r4/release_config/release_config_flow.drawio")
sq3.save_svg("/home/mao/code/android-16.0.0_r4/release_config/release_config_flow.svg")
print("Saved flow sequence")
